apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: containers-course
build:
  artifacts:
    # Set the image to build
  - image: demo-app
    jib:
      # Start from a base image
      fromImage: eclipse-temurin:21

manifests:
  kustomize:
    paths:
    - ./k8s/dev

profiles:
  - name: prod
    manifests:
      kustomize:
        paths:
        - ./k8s/prod
